"""
Korean Seasonal Event Matrix
Defines recurring yearly events with product keywords and lead times.
lead_time_days = days before peak to start campaign prep (D-X)
"""

SEASON_MATRIX = [
    # ── Spring (3–5월) ────────────────────────────────────────────────────────
    {
        "key": "spring_back_to_school",
        "name": "신학기·입학",
        "season": "spring",
        "peak_month": 3, "peak_day": 2,
        "lead_time_days": 35,
        "keywords": ["입학", "신학기", "학용품", "책가방", "문구", "어린이", "초등", "유아", "키즈"],
        "product_categories": ["육아", "kids", "lifestyle"],
        "trend_score": 8.2,
        "description": "3월 입학 시즌. 어린이·육아 제품 수요 급증, 키즈 인플루언서 협업 최적기.",
    },
    {
        "key": "spring_fine_dust",
        "name": "봄 황사·미세먼지",
        "season": "spring",
        "peak_month": 4, "peak_day": 1,
        "lead_time_days": 30,
        "keywords": ["마스크", "황사", "미세먼지", "공기청정기", "필터", "비강세정", "KF94", "공기"],
        "product_categories": ["건강", "health", "리빙", "living", "home"],
        "trend_score": 8.5,
        "description": "3–5월 황사 절정. 마스크·공기청정기 수요 급등. 건강/리빙 제품 협업 타이밍.",
    },
    {
        "key": "spring_allergy",
        "name": "봄철 알레르기·환절기 피부",
        "season": "spring",
        "peak_month": 4, "peak_day": 10,
        "lead_time_days": 25,
        "keywords": ["알레르기", "비염", "꽃가루", "환절기", "민감성", "피부트러블", "가려움", "아토피"],
        "product_categories": ["건강", "health", "뷰티", "beauty"],
        "trend_score": 7.6,
        "description": "봄철 알레르기·비염 시즌. 건강기능식품, 민감성 피부 제품 협업 기회.",
    },
    {
        "key": "spring_picnic",
        "name": "봄나들이·피크닉",
        "season": "spring",
        "peak_month": 4, "peak_day": 20,
        "lead_time_days": 30,
        "keywords": ["피크닉", "도시락", "돗자리", "나들이", "텀블러", "보냉", "캠핑", "봄"],
        "product_categories": ["식품", "food", "주방", "리빙", "living"],
        "trend_score": 7.8,
        "description": "4–5월 나들이 성수기. 도시락·보냉·피크닉 용품 SNS 콘텐츠 활발.",
    },

    # ── Summer (6–8월) ────────────────────────────────────────────────────────
    {
        "key": "summer_uv_diet",
        "name": "여름 다이어트·선케어",
        "season": "summer",
        "peak_month": 6, "peak_day": 10,
        "lead_time_days": 40,
        "keywords": ["다이어트", "선크림", "자외선", "UV", "슬리밍", "바디케어", "여름몸매", "디톡스"],
        "product_categories": ["다이어트", "diet", "뷰티", "beauty", "건강"],
        "trend_score": 8.5,
        "description": "6월 여름 준비 수요 급증. 다이어트·선케어는 5월부터 집중 공략 필요.",
    },
    {
        "key": "summer_monsoon",
        "name": "장마·제습",
        "season": "summer",
        "peak_month": 7, "peak_day": 5,
        "lead_time_days": 30,
        "keywords": ["장마", "제습기", "제습", "우산", "방수", "습기", "곰팡이", "빨래"],
        "product_categories": ["리빙", "living", "가전", "home"],
        "trend_score": 8.8,
        "description": "6말–7월 장마 시즌. 제습기·방수 제품 공구 최성수기.",
    },
    {
        "key": "summer_cooling",
        "name": "열대야·냉방·쿨링",
        "season": "summer",
        "peak_month": 7, "peak_day": 25,
        "lead_time_days": 30,
        "keywords": ["선풍기", "에어컨", "쿨링", "냉감", "열대야", "더위", "냉방", "아이스"],
        "product_categories": ["가전", "리빙", "living", "home"],
        "trend_score": 9.0,
        "description": "7–8월 열대야 절정. 쿨링 제품군은 최고 수요. 협업 전환율 가장 높은 시즌.",
    },
    {
        "key": "summer_outdoor",
        "name": "여름 휴가·아웃도어",
        "season": "summer",
        "peak_month": 8, "peak_day": 1,
        "lead_time_days": 35,
        "keywords": ["여행", "휴가", "해수욕", "캠핑", "등산", "스포츠", "아웃도어", "워터파크"],
        "product_categories": ["식품", "리빙", "패션", "fashion"],
        "trend_score": 7.9,
        "description": "7–8월 여름 휴가 시즌. 캠핑·아웃도어·여행 용품 공구 협업 기회.",
    },

    # ── Fall (9–11월) ─────────────────────────────────────────────────────────
    {
        "key": "fall_chuseok",
        "name": "추석·명절 선물세트",
        "season": "fall",
        "peak_month": 9, "peak_day": 17,
        "lead_time_days": 45,
        "keywords": ["추석", "명절", "선물세트", "선물", "세트", "명절선물", "한가위", "포장"],
        "product_categories": ["식품", "food", "건강", "health"],
        "trend_score": 9.5,
        "description": "추석 최소 45일 전 캠페인 시작 필수. 식품·건강기능식품 선물세트 최대 성수기.",
    },
    {
        "key": "fall_dry_skin",
        "name": "환절기 건조·보습",
        "season": "fall",
        "peak_month": 10, "peak_day": 10,
        "lead_time_days": 30,
        "keywords": ["보습", "수분크림", "건조", "환절기", "로션", "바디로션", "립밤", "핸드크림", "세라마이드"],
        "product_categories": ["뷰티", "beauty"],
        "trend_score": 8.0,
        "description": "10–11월 건조한 가을. 보습 제품 수요 급증. 뷰티 인플루언서 활용 최적기.",
    },
    {
        "key": "fall_camping",
        "name": "가을 캠핑·아웃도어",
        "season": "fall",
        "peak_month": 10, "peak_day": 15,
        "lead_time_days": 30,
        "keywords": ["캠핑", "단풍", "등산", "트레킹", "아웃도어", "바베큐", "캠핑용품"],
        "product_categories": ["리빙", "식품", "food", "living"],
        "trend_score": 7.8,
        "description": "9–11월 캠핑 황금 시즌. 캠핑·요리 관련 제품 협업 수요 높음.",
    },

    # ── Winter (12–2월) ───────────────────────────────────────────────────────
    {
        "key": "winter_year_end_gifts",
        "name": "연말·크리스마스 선물",
        "season": "winter",
        "peak_month": 12, "peak_day": 20,
        "lead_time_days": 45,
        "keywords": ["크리스마스", "연말", "선물", "파티", "홀리데이", "연말선물", "크리스마스선물"],
        "product_categories": ["식품", "food", "뷰티", "beauty", "리빙"],
        "trend_score": 9.0,
        "description": "11–12월 연말 선물 시즌. 모든 카테고리 협업 활발. 브랜드 홍보 최적기.",
    },
    {
        "key": "winter_heating",
        "name": "겨울 난방·보온",
        "season": "winter",
        "peak_month": 12, "peak_day": 5,
        "lead_time_days": 35,
        "keywords": ["난방", "전기장판", "전기담요", "핫팩", "히터", "보온", "방한", "온열"],
        "product_categories": ["가전", "리빙", "living", "home"],
        "trend_score": 8.8,
        "description": "11–12월 급격한 기온 하락. 보온·난방 제품 공구 수요 급등.",
    },
    {
        "key": "winter_moisturize",
        "name": "겨울 건조·가습",
        "season": "winter",
        "peak_month": 12, "peak_day": 15,
        "lead_time_days": 30,
        "keywords": ["가습기", "건조", "보습", "수분", "립밤", "핸드크림", "오일"],
        "product_categories": ["가전", "home", "뷰티", "beauty"],
        "trend_score": 8.0,
        "description": "겨울 실내 건조 심화. 가습기·보습 제품 동시 수요 급증.",
    },
    {
        "key": "winter_new_year",
        "name": "설날·구정 선물세트",
        "season": "winter",
        "peak_month": 2, "peak_day": 1,
        "lead_time_days": 45,
        "keywords": ["설날", "구정", "설선물", "명절선물", "선물세트", "새해", "신정"],
        "product_categories": ["식품", "food", "건강", "health"],
        "trend_score": 9.3,
        "description": "설날 45일 전 준비 시작 필수. 추석과 함께 최대 공구 시즌.",
    },
    {
        "key": "winter_indoor",
        "name": "겨울 집콕·홈트·취미",
        "season": "winter",
        "peak_month": 1, "peak_day": 20,
        "lead_time_days": 30,
        "keywords": ["홈트", "운동기구", "요가", "필라테스", "집콕", "실내운동", "취미", "홈피트니스"],
        "product_categories": ["건강", "health", "리빙", "lifestyle"],
        "trend_score": 7.5,
        "description": "1–2월 추운 겨울 실내 활동 증가. 홈트·취미 제품 협업 기회.",
    },
]

SEASON_LABELS = {
    "spring": {"label": "봄", "color": "green"},
    "summer": {"label": "여름", "color": "blue"},
    "fall":   {"label": "가을", "color": "amber"},
    "winter": {"label": "겨울", "color": "purple"},
}
